spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5434/json-parser-db
    username: user
    password: password_2020
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: ddl-auto=update